#!/usr/bin/env bash
# Claude Code PostToolUse hook — fires after Edit or Write calls.
# When an artefact generated by AIUP commands is created or modified, reminds
# the agent to update traceability in REQUIREMENTS.md.
#
# Input: JSON on stdin with { tool_name, tool_input: { file_path }, tool_output }
# Output: context string on stdout to inject into conversation.

set -euo pipefail

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
# shellcheck source=traceability-artefacts.sh
source "$SCRIPT_DIR/traceability-artefacts.sh"

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ]; then
    exit 0
fi

classify_traceability_artefact "$FILE_PATH" || exit 0

PROJECT_DIR=$(pwd)
REQ_FILE=""
for candidate in "$PROJECT_DIR/REQUIREMENTS.md" "$PROJECT_DIR/docs/REQUIREMENTS.md"; do
    if [ -f "$candidate" ]; then
        REQ_FILE="$candidate"
        break
    fi
done

if [ -z "$REQ_FILE" ]; then
    exit 0
fi

echo "Artefact of type '$ARTEFACT_TYPE' was written to $FILE_PATH. Update the traceability section in $REQ_FILE to reflect this generated artefact."
exit 0
